GET http://localhost:3000/users
Authorization: Barear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjg4LCJuYW1lIjoiQWRhbSIsImVtYWlsIjoiYWRhbUBnbWFpbC5jb20iLCJpYXQiOjE2OTA3MTI5MDUsImV4cCI6MTY5MDcxMjkyMH0.wdRvR4V0crVtbd3UhwKoje1X1_YZUq6SiHOruLoy4wo

#########
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "wisnu",
    "email": "wisnu@gmail.om",
    "password": "1234",
    "confPassword": "1234"
}

#########
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "adam@gmail.com",
    "password": "adam123"
}

#########
GET http://localhost:3000/token
#########
DELETE http://localhost:3000/logout