GET http://localhost:3000/users
Authorization: Barear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjkwLCJuYW1lIjoiQXVyb3JhIiwiZW1haWwiOiJhdXJvcmFAZ21haWwuY29tIiwiaWF0IjoxNjkwODgwMDI0LCJleHAiOjE2OTA4ODAwMzl9.myr-xqSuR18yMX0fVsEfyRPBcB-PElQG9W2MAjhvkBM

#########
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Rangga",
    "email": "rangga@gmail.com",
    "password": "rangga123",
    "confPassword": "rangga123"
}

#########
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "aurora@gmail.com",
    "password": "aurora123"
}

#########
GET http://localhost:3000/token
#########
DELETE http://localhost:3000/logout